import { Router } from 'express';
import { contentController } from '../controllers/contentController';
import { uploadSingle, uploadMultiple } from '../middleware/upload';
import { authenticateAdmin } from '../middleware/adminAuth';
const router = Router();
router.get('/categories', contentController.getCategories);
router.get('/categories/:id', contentController.getCategoryById);
router.get('/properties', contentController.getProperties);
router.get('/properties/featured', contentController.getFeaturedProperties);
router.get('/properties/region/:region', contentController.getPropertiesByRegion);
router.get('/properties/category/:categoryId', contentController.getPropertiesByCategory);
router.get('/properties/type/:type', contentController.getPropertiesByType);
router.get('/properties/search', contentController.searchProperties);
router.get('/properties/:id', contentController.getPropertyById);
router.post('/admin/categories', authenticateAdmin, uploadSingle, contentController.createCategory);
router.put('/admin/categories/:id', authenticateAdmin, uploadSingle, contentController.updateCategory);
router.delete('/admin/categories/:id', authenticateAdmin, contentController.deleteCategory);
router.post('/admin/properties', authenticateAdmin, uploadMultiple, contentController.createProperty);
router.put('/admin/properties/:id', authenticateAdmin, uploadMultiple, contentController.updateProperty);
router.delete('/admin/properties/:id', authenticateAdmin, contentController.deleteProperty);
export default router; 